import { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Spotify',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body className="bg-zinc-900 text-zinc-50 p-20 h-screen">{children}</body>
    </html>
  )
}
